### ISSUE TITLE
Question/Feature request: Do you consider adding pathfinding to rapier ?

### ISSUE THREAD

**Issue by Illthiriel** [dimforge/rapier#105]
Hello,
thanks for the amazing work you are doing ! and sorry if it's not the proper channel to ask my question.

Do you consider adding pathfinding to rapier ?

I think it would make sense consider rapier already manage 'filled space' though Collider.

**Comment by sebcrozet** [comment]
Hi!
Right now I believe this is a little out of the scope of a physics engine. I don't believe there is any benefit to add this to Rapier instead of a separate crate.

**Comment by sebcrozet** [comment]
Closing this as this there is no plane to add this currently.
