### ISSUE TITLE
Initial pipeline step is extremely slow.

### ISSUE THREAD

**Issue by zakarumych** [dimforge/rapier#106]
If I spawn multiple cones at identical location then initial `PhysicsPipeline::step` takes much more time that it should.

In debug mode with 10 cones first step takes 15 seconds, 15 cones - 30 seconds, 20 cones - 60 seconds.
In release it's much faster, but still way too slow: 100 cones - 12 seconds, 200 cones - 47 seconds.
All this time one core is fully utilized by the process.

It only happens if cones all are at same location.
I also tried other simple colliders like ball or cuboid, and everything works smooth with them.

**Comment by zakarumych** [comment]
Repro: https://github.com/zakarumych/rapier-slow-step

**Comment by sebcrozet** [comment]
Hi! If they are all spawned at the same location, then the complexity of collision detection is quadratic (i.e. everything touches everything). The collision-detection algorithm for cuboids and balls are significantly faster than the one for cones, cylinders, and convex polyhedrons. Also if all the cones are identical, then this makes it a degenerate case from the point of view of that collision-detection algorithm, making it even slower. So I guess the kind of performance you are seeing isn’t surprising.

**Comment by sebcrozet** [comment]
Closing this as I think this is a non-issue, considering it happens in a situation that should not happen in any realistic application.
Feel free to reopen with the description of an use-case if this affects you.
