### ISSUE TITLE
Example request: export/import world state

### ISSUE THREAD

**Issue by lestofante** [dimforge/rapier#111]
I would like a way to export and import the complete world state so it can easily be saved and restored, this would make possible to easily save to file or over the network the simulation state, and thus make full use of the deterministic aspect of the game.  
  
This is because for a user of the engine is basically impossible to know exactly what should be saved and how to restore it, plus those things can change between versions and "silently" breaking the synchronization/determinism.

Note that compatibility between different engine version, while nice to have, is not a requirement for this Feature Request.

**Comment by extrawurst** [comment]
this is already easily possible. rapier crate supports a `feature` called `serde-serialize` and with that the relevant types like `RigidBodySet`,`ColliderSet` etc. become easily serializable/deserializable

**Comment by lestofante** [comment]
thanks, i am having an hard time to find out what should be serialized to save and load a world. Is there any example/tutorial?
So far on discord i found:  "Serialize the RigidBodySet, ColliderSet, JointSet, NarrowPhase, BroadPhase using serde."
Ill try to come up with an example and post it there for confirmation and maybe can be help other too, changing the title of the issue to reflect this

**Comment by extrawurst** [comment]
@lestofante feel free to checkout my example for *saving state* in order to be able to verify determinism in rapier in this example repo: https://github.com/extrawurst/rapier-determinism

here is the relevant code: https://github.com/extrawurst/rapier-determinism/blob/master/logic/src/rapier_world.rs#L130

**Comment by lestofante** [comment]
Thank you!
I guess the magic is all there:

            let mut pipeline = self.pipeline.borrow_mut();
            let mut broad_phase = self.broad_phase.borrow_mut();
            let mut narrow_phase = self.narrow_phase.borrow_mut();
            let mut bodies = self.bodies.borrow_mut();
            let mut colliders = self.colliders.borrow_mut();
            let mut joints = self.joints.borrow_mut();

            let gravity = na::Vector2::new(self.gravity.x, self.gravity.y);
            let mut integration_parameters = IntegrationParameters::default();
            integration_parameters.max_position_iterations = 1;
            integration_parameters.max_linear_correction = 1.;

            let event_handler = RapierEventHandler {};

            pipeline.step(
                &gravity,
                &integration_parameters,
                &mut broad_phase,
                &mut narrow_phase,
                &mut bodies,
                &mut colliders,
                &mut joints,
                None,
                None,
                &event_handler,
            );

and all of those are input/output parameter. Thanks
