### ISSUE TITLE
Panic in VelocityGroundConstraint::warmstart

### ISSUE THREAD

**Issue by mwillsey** [dimforge/rapier#113]
Hello!

I'm getting a panic in `VelocityGroundConstraint::warmstart` in what I think is pretty vanilla usage of `bevy_rapier2d`.

Repro is [here](https://github.com/mwillsey/silly-bevy-thing/tree/9e4f89487330f2214446fed4cdf2a349253b7da6), just `RUST_BACKTRACE=1 cargo run`. There should be some rectangles on screen and then it should crash within a few seconds.

<details>
  <summary>Backtrace</summary>
<pre>
thread 'main' panicked at 'index out of bounds: the len is 2 but the index is 54', /Users/mwillsey/.cargo/git/checkouts/rapier-1eded0a3355a18db/3be8669/build/rapier2d/../../src/dynamics/solver/velocity_ground_constraint.rs:227:9
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::panic_bounds_check
   3: rapier2d::dynamics::solver::velocity_ground_constraint::VelocityGroundConstraint::warmstart
             at /Users/mwillsey/.cargo/git/checkouts/rapier-1eded0a3355a18db/3be8669/build/rapier2d/../../src/dynamics/solver/velocity_ground_constraint.rs:227:9
   4: rapier2d::dynamics::solver::velocity_solver::VelocitySolver::solve
             at /Users/mwillsey/.cargo/git/checkouts/rapier-1eded0a3355a18db/3be8669/build/rapier2d/../../src/dynamics/solver/velocity_solver.rs:55:13
   5: rapier2d::dynamics::solver::island_solver::IslandSolver::solve_island
             at /Users/mwillsey/.cargo/git/checkouts/rapier-1eded0a3355a18db/3be8669/build/rapier2d/../../src/dynamics/solver/island_solver.rs:49:13
   6: rapier2d::pipeline::physics_pipeline::PhysicsPipeline::step
             at /Users/mwillsey/.cargo/git/checkouts/rapier-1eded0a3355a18db/3be8669/build/rapier2d/../../src/pipeline/physics_pipeline.rs:173:17
   7: bevy_rapier2d::physics::systems::step_world_system
             at /Users/mwillsey/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_rapier2d-0.8.0/src/physics/systems.rs:227:9
   8: core::ops::function::Fn::call
             at /Users/mwillsey/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/ops/function.rs:70:5
   9: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &F>::call_mut
             at /Users/mwillsey/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/ops/function.rs:247:13
  10: <Func as bevy_ecs::system::into_system::IntoSystem<(A,B,C,D,E,F,G,H,I,J),bevy_ecs::system::into_system::FuncSystem<Out>>>::system::{{closure}}
             at /Users/mwillsey/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_ecs-0.4.0/src/system/into_system.rs:237:38
  11: bevy_ecs::schedule::stage_executor::ParallelSystemStageExecutor::run_systems::{{closure}}::{{closure}}
             at /Users/mwillsey/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_ecs-0.4.0/src/schedule/stage_executor.rs:372:29
  12: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/core/src/future/mod.rs:80:19
  13: async_executor::Executor::spawn::{{closure}}
             at /Users/mwillsey/.cargo/registry/src/github.com-1ecc6299db9ec823/async-executor-1.4.0/src/lib.rs:138:13
  14: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/core/src/future/mod.rs:80:19
  15: async_task::raw::RawTask<F,T,S>::run
             at /Users/mwillsey/.cargo/registry/src/github.com-1ecc6299db9ec823/async-task-4.0.3/src/raw.rs:489:20
  16: async_executor::Executor::try_tick
             at /Users/mwillsey/.cargo/registry/src/github.com-1ecc6299db9ec823/async-executor-1.4.0/src/lib.rs:175:17
  17: bevy_tasks::task_pool::TaskPool::scope
             at /Users/mwillsey/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_tasks-0.4.0/src/task_pool.rs:212:17
  18: bevy_ecs::schedule::stage_executor::ParallelSystemStageExecutor::run_systems
             at /Users/mwillsey/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_ecs-0.4.0/src/schedule/stage_executor.rs:300:9
  19: <bevy_ecs::schedule::stage_executor::ParallelSystemStageExecutor as bevy_ecs::schedule::stage_executor::SystemStageExecutor>::execute_stage
             at /Users/mwillsey/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_ecs-0.4.0/src/schedule/stage_executor.rs:496:13
  20: bevy_ecs::schedule::stage::SystemStage::run_once
             at /Users/mwillsey/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_ecs-0.4.0/src/schedule/stage.rs:102:9
  21: <bevy_ecs::schedule::stage::SystemStage as bevy_ecs::schedule::stage::Stage>::run
             at /Users/mwillsey/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_ecs-0.4.0/src/schedule/stage.rs:136:21
  22: bevy_ecs::schedule::Schedule::run_once
             at /Users/mwillsey/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_ecs-0.4.0/src/schedule/mod.rs:149:13
  23: <bevy_ecs::schedule::Schedule as bevy_ecs::schedule::stage::Stage>::run
             at /Users/mwillsey/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_ecs-0.4.0/src/schedule/mod.rs:189:21
  24: bevy_winit::winit_runner::{{closure}}
             at /Users/mwillsey/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_winit-0.4.0/src/lib.rs:371:17
  25: <alloc::boxed::Box<F,A> as core::ops::function::FnMut<Args>>::call_mut
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/alloc/src/boxed.rs:1314:9
  26: <winit::platform_impl::platform::app_state::EventLoopHandler<T> as winit::platform_impl::platform::app_state::EventHandler>::handle_nonuser_event
             at /Users/mwillsey/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.24.0/src/platform_impl/macos/app_state.rs:71:9
  27: winit::platform_impl::platform::app_state::Handler::handle_nonuser_event
             at /Users/mwillsey/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.24.0/src/platform_impl/macos/app_state.rs:173:21
  28: winit::platform_impl::platform::app_state::AppState::cleared
             at /Users/mwillsey/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.24.0/src/platform_impl/macos/app_state.rs:331:13
  29: <unknown>
  30: <unknown>
  31: <unknown>
  32: <unknown>
  33: <unknown>
  34: <unknown>
  35: <unknown>
  36: <unknown>
  37: <unknown>
  38: <unknown>
  39: <() as objc::message::MessageArguments>::invoke
             at /Users/mwillsey/.cargo/registry/src/github.com-1ecc6299db9ec823/objc-0.2.7/src/message/mod.rs:128:17
  40: objc::message::platform::send_unverified
             at /Users/mwillsey/.cargo/registry/src/github.com-1ecc6299db9ec823/objc-0.2.7/src/message/apple/mod.rs:27:9
  41: objc::message::send_message
             at /Users/mwillsey/.cargo/registry/src/github.com-1ecc6299db9ec823/objc-0.2.7/src/message/mod.rs:178:5
  42: winit::platform_impl::platform::event_loop::EventLoop<T>::run_return
             at /Users/mwillsey/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.24.0/src/platform_impl/macos/event_loop.rs:106:25
  43: winit::platform_impl::platform::event_loop::EventLoop<T>::run
             at /Users/mwillsey/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.24.0/src/platform_impl/macos/event_loop.rs:93:9
  44: winit::event_loop::EventLoop<T>::run
             at /Users/mwillsey/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.24.0/src/event_loop.rs:154:9
  45: bevy_winit::run
             at /Users/mwillsey/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_winit-0.4.0/src/lib.rs:121:5
  46: bevy_winit::winit_runner
             at /Users/mwillsey/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_winit-0.4.0/src/lib.rs:379:9
  47: core::ops::function::Fn::call
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/core/src/ops/function.rs:70:5
  48: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/alloc/src/boxed.rs:1321:9
  49: bevy_app::app::App::run
             at /Users/mwillsey/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_app-0.4.0/src/app.rs:67:9
  50: bevy_app::app_builder::AppBuilder::run
             at /Users/mwillsey/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_app-0.4.0/src/app_builder.rs:49:9
  51: my_bevy_game::main
             at ./src/main.rs:502:5
  52: core::ops::function::FnOnce::call_once
             at /Users/mwillsey/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
</pre>
</details>

The bug seems to be dependent on [line 237](https://github.com/mwillsey/silly-bevy-thing/blob/9e4f89487330f2214446fed4cdf2a349253b7da6/src/main.rs#L237); if you comment it out, change the impulse parameters, or even just take it out of the `if` condition, it seems to work.

**Comment by darzu** [comment]
I minified the repo (by removing our other game clutter):
https://github.com/mwillsey/silly-bevy-thing/tree/rapier_crash_repro
this line: https://github.com/mwillsey/silly-bevy-thing/blob/rapier_crash_repro/src/main.rs#L50

Here are the surrounding lines. Interesting to note that if the if statement is removed, the crash goes away.
```
...
                let blob_rb = &mut rigid_bodies[blob_rbh.handle()];
                if !blob_rb.is_moving() /*|| true*/ { // NOTE: adding `|| true` here causes it not to crash.
                    // ---
                    // CRASH! This line. Comment out to hide crash
                    blob_rb.apply_impulse([100.0, 100.0].into(), true);
                    // CRASH! This line. Comment out to hide crash
                    // ---
                }
...
```

**Comment by darzu** [comment]
Someone helped us find a workaround:
```
diff --git a/src/main.rs b/src/main.rs
index 186d8af..a2e1781 100644
--- a/src/main.rs
+++ b/src/main.rs
@@ -117,7 +117,10 @@ fn spawn_blob<'a>(
         blob_size,
         blob_size,
         true,
-        |rig| rig.mass(0.1),
+        |rig| 
+            rig.mass(0.1)
+                // WORK AROUND FOR: https://github.com/mwillsey/silly-bevy-thing/blob/rapier_crash_repro/src/main.rs#L50
+                .can_sleep(false),
         |col| {
             col.collision_groups(InteractionGroups::new(ALL_GRP, ALL_GRP))
                 .friction(0.2)
```

**Comment by guccialex** [comment]
Sorry. I'm having the same error, and im having trouble figuring out what the workaround is that you posted

Is it the .can_sleep being set false? I have that and im still getting 

![Screenshot from 2021-03-25 21-31-22](https://user-images.githubusercontent.com/30034696/112564938-84677580-8db2-11eb-8b5c-5a5146406585.png)
