### ISSUE TITLE
Missing docs: sensors

### ISSUE THREAD

**Issue by emilk** [dimforge/rapier#117]
It seems like sensors doesn't contribute any mass to the bodies they are attached to. This tripped me up, as I don't see it mentioned anywhere in <https://www.rapier.rs/docs/user_guides/rust/event_handling_and_sensors> nor in <https://docs.rs/rapier3d/0.5.0/rapier3d/geometry/struct.ColliderBuilder.html#method.sensor>.

**Comment by Ralith** [comment]
The linked method's docs now include the line:

> Sensors will have a default density of zero, but if you call Self::mass_properties you can assign a mass to a sensor.

Should this be closed?

**Comment by sebcrozet** [comment]
Sensors now contribute to the rigid-body mass too, for consistency with non-sensor colliders.
