### ISSUE TITLE
Modify existing joints

### ISSUE THREAD

**Issue by emilk** [dimforge/rapier#121]
Now that joint motos are merged (https://github.com/dimforge/rapier/pull/119) it would be beneficial to be able to modify existing joints, e.g. to change the joint motor targets. Unlike `RigidBodySet` and `ColliderSet`, `JointSet` has no `get_mut` member. I don't know if this is an oversight, or a deliberate choice.

**Comment by sebcrozet** [comment]
Yes, this is an oversight. There is a `JointSet::iter_mut` method but we are missing `JointSet::get_mut` and `JointSet::get_unknown_gen_mut`.
