### ISSUE TITLE
No way of seting the friction CoefficientCombineRule

### ISSUE THREAD

**Issue by lassade** [dimforge/rapier#127]
There is no way of setting the `CoefficientCombineRule` for friction or restitution;

Can the collider flags be exposed or setted indirectly by a function?

**Comment by sebcrozet** [comment]
Hi! The friction and restitution combine rules can already be set when building the collider with:
- [`ColliderBuilder::friction_combine_rule`](https://docs.rs/rapier3d/0.6.1/rapier3d/geometry/struct.ColliderBuilder.html#method.friction_combine_rule).
- [`ColliderBuilder::restitution_combine_rule`](https://docs.rs/rapier3d/0.6.1/rapier3d/geometry/struct.ColliderBuilder.html#method.restitution_combine_rule).

> Can the collider flags be exposed or setted indirectly by a function?

The collider flags are reserved to an internal use only.

**Comment by lassade** [comment]
I know, sorry forgot to mention, that I want to set it on a existing collider. While using bevy_rapier the `ColliderBuilder` component gets repalce by a `ColliderHandleComponent`, the `Collider` gotten from `ColliderSet` have no sutch methods;

**Comment by sebcrozet** [comment]
Ok! The `Collider` does not support changing the combine rule after its creation right now. This requires some extra work that is not yet implemented.
