### ISSUE TITLE
Add a function returning the version of Rapier.

### ISSUE THREAD

**Issue by sebcrozet** [dimforge/rapier#13]
We need a function or constant that returns the version of Rapier. This can be useful for networked applications to check that they all use the same version of the crate. Ideally we would want this version information to include the enabled features of the crate too.

**Comment by dpmkl** [comment]
Would the built in cargo version do? Would be rather simple and straight forward using something like this: 

`
let version = env!("CARGO_PKG_VERSION");
`

**Comment by sebcrozet** [comment]
@dpmkl Yes, this looks like what we need.
