### ISSUE TITLE
Feature : Allow for collision detection without physics simulation

### ISSUE THREAD

**Issue by rishflab** [dimforge/rapier#145]
## Problem

Currently there is no way to get to do collision detection without physics simulation. If I want to get collision events on my player, I have to use a dynamic rigidbody which is rarely desirable in games.

In games you usually want the  movement of entities to be controlled by game logic, not the physics engine. The "physics" engine is primary used to get a list of intersection/contact results to decide what game logic to execute. There are games where dynamic bodies are used for player controller entities but this is usually limited to racing/flight sim type games.

Currently the query pipeline can be used to query each shape against the rest but this can result in redundant queries.

## Desired Feature
A collision pipeline with a method to find all contacts/intersections. Support for interactions groups would also be great.

**Comment by sdfgeoff** [comment]
Question from an inexperienced user: How is this different to using BodyType::KinematicBody for all relevant objects? (And hooking up the an EventHandler). As far as I understand, a KinematicBody is a body that detects collisions but is not affected by the simulation.

**Comment by edgarssilva** [comment]
Yeah I've been looking for this as well, I only really need hitboxes and contact listeners between them.
Maybe providing a way to only implement Parry would be an alternative.

**Comment by maniwani** [comment]
Have you tried the `CollisionPipeline`? 
<https://docs.rs/rapier2d/0.11.0/rapier2d/pipeline/struct.CollisionPipeline.html>
<https://docs.rs/rapier3d/0.11.0/rapier3d/pipeline/struct.CollisionPipeline.html>

**Comment by edgarssilva** [comment]
Yeah since then I have, but since I'm using bevy and working with different libraries like heron and they don't have direct support but I will implement them down the line if I can :)

**Comment by sebcrozet** [comment]
Closing this since we have the `CollisionPipeline` now.

**Comment by mrchantey** [comment]
Here's a bevy example for a bundle where two kinematic colliders will trigger a collision event:

```rust
use bevy::prelude::*;
use bevy_rapier3d::prelude::*;

#[derive(Bundle)]
pub struct ColliderBundle {
	pub collider: Collider,
	pub rigidbody: RigidBody,
	pub active_events: ActiveEvents,
	pub active_collision_types: ActiveCollisionTypes,
}

impl ColliderBundle {
	pub fn new(collider: Collider) -> Self {
		Self {
			collider,
			rigidbody: RigidBody::KinematicPositionBased,
			active_events: ActiveEvents::COLLISION_EVENTS,
			active_collision_types: ActiveCollisionTypes::default()
				| ActiveCollisionTypes::KINEMATIC_KINEMATIC,
		}
	}
}



pub fn display_events(mut collision_events: EventReader<CollisionEvent>) {
	for collision_event in collision_events.iter() {
		println!("Received collision event: {:?}", collision_event);
	}
}


```
