### ISSUE TITLE
Feature: Add set_position_wrt_parent() to Collider

### ISSUE THREAD

**Issue by rishflab** [dimforge/rapier#151]
Currently we can mutate the position of a `RigidBody` after it has been built. It would be nice to have this functionality on `Collider` as well. This will allow attaching hitbox colliders to the joints of a skeletal rig, which can move independently without having to create multiple rigid bodies.

**Comment by sebcrozet** [comment]
While we can't add `.set_position()` directly, we can add `.set_position_wrt_parent()` (I modified the issue title accordingly) which updates the position of the the collider relative to the rigid-body it is attached to.

To make this work properly we need to make sure the parent's rigid-body's mass properties are updated accordingly after this position change.

**Comment by pinkponk** [comment]
I know this is closed but I'm trying to scale a object in a game and I cannot manage to change the relative collider position after spawn. The scale of the collider is updated automatically but the translation is not effected when changing the relative position using the Transform
![Screenshot from 2022-06-01 12-53-11](https://user-images.githubusercontent.com/14301446/171388406-b453c23a-1067-4fa0-b985-36dada6668f6.png)
![Screenshot from 2022-06-01 12-52-31](https://user-images.githubusercontent.com/14301446/171388411-21677ef7-40cc-4315-8e0b-7248327ca17f.png)
.

**Comment by pinkponk** [comment]
I "solved" this by simply despawning the entity with the collider and the transform in order to get the correct relative positio
![Screenshot from 2022-06-01 13-51-49](https://user-images.githubusercontent.com/14301446/171398175-d8d0ab84-7015-4d4b-9268-7a6855473fdb.png)
n
