### ISSUE TITLE
Add a way to modify InteractionGroups on a Collider

### ISSUE THREAD

**Issue by mystal** [dimforge/rapier#155]
I'm porting a game from `nphysics` to `rapier`. In `nphysics` Colliders have a `set_collision_groups` method to modify their collision groups. I don't see any way to do the same thing in `rapier`.

This is a really useful feature for my game, as I have colliders that I want whose groups I want to modify during gameplay to enable/disable certain collisions. One example is a dash the player can perform that allows them to move through enemies that would normally block them.

**Comment by sebcrozet** [comment]
Hi! This will be added as part as this week's release.

**Comment by mystal** [comment]
That's great news! Thanks so much for all your hard work <3
