### ISSUE TITLE
? Aerodynamics

### ISSUE THREAD

**Issue by Zentropivity** [dimforge/rapier#184]
Are there plans to introduce aerodynamics simulation into the system?
It would be cool to be able to model a plane and have it fly.

**Comment by Ralith** [comment]
That's a huge can of worms that I think would be best handled in a separate crate, responsible for computing forces that you can then pass into rapier.

**Comment by sebcrozet** [comment]
I agree with @Ralith. Chances are that you don't need this to be part of Rapier itself, just like fluids simulation.
Closing this as I don't think this will happen as part of Rapier itself.
