### ISSUE TITLE
Make Parry dependency optional to allow integration of third-party collision detection

### ISSUE THREAD

**Issue by HackerFoo** [dimforge/rapier#202]
I'd like to use Rapier without Parry (for 3D) because I already have a data structure optimized for both shape representation and collision detection, with my own GJK implementation.

Currently, I'm implementing `Shape` for the convex subcomponents and `Compound` to compose them, which works well enough for now, I'd rather not build a redundant bounding volume hierarchy.

**Comment by HackerFoo** [comment]
See here for a [demo video](https://youtu.be/wjmWTJVkyqg).

**Comment by sebcrozet** [comment]
Hi! There is no plan to make the Parry dependency optional. This would be quite complicated, and Parry already provides abstractions for integrating third-party collision detection:
1. Define your own shape types (including a shape that would replace `Compound`) by implementing the `Shape` trait.
2. Provide your own collision-detection algorithm by implementing the [PersistantQueryDispatcher trait](https://docs.rs/parry3d/0.5.1/parry3d/query/trait.PersistentQueryDispatcher.html) and constructing the Rapier's `NarrowPhase` [with `NarrowPhase::with_query_dispatcher](https://docs.rs/rapier3d/0.9.2/rapier3d/geometry/struct.NarrowPhase.html#method.with_query_dispatcher).

As an example, you may want to take a look at the [planetmap project](https://github.com/Ralith/planetmap/blob/master/src/parry.rs) which provides its own shape for procedurally-generated planets and its own query dispatcher as well.

**Comment by HackerFoo** [comment]
I'm closing this, because there seems to be nothing to be done on this issue, and I don't need it anymore. Thanks!
