### ISSUE TITLE
Allow users to specify mass, instead of density, when adding a collider

### ISSUE THREAD

**Issue by ssbr** [dimforge/rapier#203]
It's a bit nonobvious how to do this, and I had to dig around a bit. Maybe it'd be worth adding `ColliderMassProps::Mass(Real)` to [`ColliderMassProps`](https://docs.rs/rapier3d/0.9.2/rapier3d/geometry/enum.ColliderMassProps.html)?

Workaround would be: if you know the mass and the shape, but not the density, you can determine the density as so:

```rs
pub fn density(mass: f32, shape: &dyn rapier::Shape) -> f32 {
    mass * shape.mass_properties(1.0).inv_mass
}
```

And then you can add your collider with that shape using `ColliderMassProps::Density` as normal:

```rs
let shape = ...;
let mass_properties = ColliderMassProps::Density(density(mass, &*shape));

// e.g. Bevy:
commands.entity(e).insert_bundle(rapier::ColliderBundle {
    shape,
    mass_properties,
    ..Default::default()
});
```

Half just posting this in case it's useful to someone else. I really struggled and felt not at all smart when I figured out the answer. (As an intermediate version of the above, I actually wrote my own volume function which checked which shape it was... ` if let Some(cu) = shape.as_cuboid() { let he = &cu.half_extents; he.x * he.y * he.z * (2.0 * 2.0 * 2.0)} else if let ...` But since Rapier needs to be able to compute the mass given the density, I realized I could find a way to write the above, instead.)

**Comment by sebcrozet** [comment]
Hi! This is what the `ColliderMassProps::MassProperties` variant is for: it lets your specify the mass and angular inertia explicitly by constructing your own [MassProperties](https://docs.rs/rapier3d/0.9.2/rapier3d/dynamics/struct.MassProperties.html#method.new).

**Comment by ssbr** [comment]
@sebcrozet I don't want to specify the angular inertia or center of mass, just the mass. :(

**Comment by sebcrozet** [comment]
Ah, so you want to specify the mass and have the center of mass and angular inertia computed automatically?
If this is the case, then, yeah, it could make sense to add a `ColliderMassProps::Mass`.
One alternative would be to do something like this:
```rust
let mut mprops = shape.mass_properties();
mprops.set_mass(mass, true);
let mass_properties = ColliderMassProps::from(mprops);
```

**Comment by ssbr** [comment]
Yes, that's right. Eitger `ColliderMassProps::Mass` or your suggested alternative would work for me, although I confess `Mass` would be much more discoverable in my view.

---

I should've posted an example, but one might be -- like, suppose I want to simulate some spinning plates, or a car tire, or a human rag doll. I can actually find the masses of these things fairly easily online (or measurable on a scale at home), but finding their density or the other massprops is much more annoying. So it's pretty tempting to assume constant density, use the mass I found on Google, and infer the com, angular inertia from the shape that I provide (which is a rough approximation of the real shape -- hopefully good enough to get roughly correct com and angular inertia figures.)

(If this process is not good enough, then I would likely want to hand-compute the mass properties in a more fine-grained way and use `ColliderMassProps::MassProperties` as you suggest -- then I wouldn't need to e.g. assume constant density.)

Density is only easily discoverable in this way when I happen to know that something is made of exactly one material, but I encounter very few of those things in real life or in games. Maybe things like furniture (mostly or entirely wood), filled containers of fluids (assuming the mass of the container is negligible).

But for the most part I have easy access to mass figures, and poor access to density figures.
