### ISSUE TITLE
Implement Default for collection types

### ISSUE THREAD

**Issue by FeldrinH** [dimforge/rapier#218]
Currently RigidBodySet, ColliderSet, JointSet, Arena, Coarena and probably other collections provided by rapier do not implement the Default trait.

This is somewhat annoying, because it prevents the use of #[derive(Default)] and other Default based conveniences for structs that consist of rapier's collections.

It is also non-idiomatic, given that all collections in std implement Default.

It would be nice if Default was implemented for all collections which support creating an empty collection with no values.

**Comment by sebcrozet** [comment]
Sounds like a good idea!

**Comment by besok** [comment]
Hey! I would like to start contributing to this lib and this issue seems like a good chance to dive in. Can it be assigned to me?
