### ISSUE TITLE
IntersectionEvent should become an enum like ContactEvent

### ISSUE THREAD

**Issue by eldyer** [dimforge/rapier#219]
For consistency reasons `IntersectionEvent` should become an enum like `ContactEvent` with `Started` and `Stopped` variants ([see Discord discussion](https://discord.com/channels/507548572338880513/747935665076830259/861953087542657084)).

**Comment by sebcrozet** [comment]
In Rapier 0.12 (non-alpha version), intersection and contact events have been combined into a single `CollisionEvent` enum.
