### ISSUE TITLE
Typo in documentation

### ISSUE THREAD

**Issue by stephanemagnenat** [dimforge/rapier#23]
There is a small typo in documentation [here](https://rapier.rs/docs/user_guides/rust/rigid_body_simulation). In sentence, *This will allow use to get a reference to this body later if needed:*, the *use* should be *us*. I've been briefly looking for the source of the documentation to correct it myself, but did not find it.

**Comment by sebcrozet** [comment]
Thank you for pointing out this error! 

> I've been briefly looking for the source of the documentation to correct it myself, but did not find it.

Yeah, that documentation has not been published to GitHub yet (when it will be, it will on another `rapier.rs` repository).

**Comment by sebcrozet** [comment]
A fix has been published.
