### ISSUE TITLE
Major cuboid-cuboid interpenetration despite CCD

### ISSUE THREAD

**Issue by Ralith** [dimforge/rapier#237]
A 0.2^3 cuboid falling onto a static 20^3 cuboid from a height of 1 unit under 9.81 units/s^2 of gravity has a minimum height of about 0.0435 above the static cuboid's face, i.e. it sinks more than a quarter of the way into the surface. Adjusting the starting height to 100 units (and the number of steps to 300) produces a minimum height of -0.433, i.e. entirely submerged in the static cuboid. The situation slowly gets resolved, but not without a significant amount of sideways motion.

Occurs on current master.

<details>
<summary>self-contained repro</summary>

```rust
use rapier3d_f64::{
    dynamics::{
        CCDSolver, IntegrationParameters, IslandManager, JointSet, RigidBodyBuilder, RigidBodySet,
        RigidBodyType,
    },
    geometry::{BroadPhase, ColliderBuilder, ColliderSet, Cuboid, NarrowPhase, SharedShape},
    pipeline::PhysicsPipeline,
};

fn main() {
    let mut islands = IslandManager::new();
    let mut bodies = RigidBodySet::new();
    let mut colliders = ColliderSet::new();

    let mut pipeline = PhysicsPipeline::new();
    let integration_parameters = IntegrationParameters::default();
    let mut broad_phase = BroadPhase::new();
    let mut narrow_phase = NarrowPhase::new();
    let mut joints = JointSet::new();
    let mut ccd_solver = CCDSolver::new();

    // Ground box with a surface facing +y at y=0
    colliders.insert(
        ColliderBuilder::new(SharedShape::new(Cuboid::new(na::Vector3::new(
            10.0, 10.0, 10.0,
        ))))
        .position(na::Isometry3::translation(0.0, -10.0, 0.0))
        .build(),
    );

    let cuboid = bodies.insert(
        RigidBodyBuilder::new(RigidBodyType::Dynamic)
            .ccd_enabled(true)
            .position(na::Isometry3::translation(0.0, 1.0, 0.0))
            .build(),
    );
    colliders.insert_with_parent(
        ColliderBuilder::new(SharedShape::new(Cuboid::new(na::Vector3::repeat(0.1)))).build(),
        cuboid,
        &mut bodies,
    );

    for i in 0..40 {
        println!("{}", i);
        pipeline.step(
            &na::Vector3::new(0.0, -9.81, 0.0),
            &integration_parameters,
            &mut islands,
            &mut broad_phase,
            &mut narrow_phase,
            &mut bodies,
            &mut colliders,
            &mut joints,
            &mut ccd_solver,
            &(),
            &(),
        );
        let cuboid = bodies.get(cuboid).unwrap();
        println!("cube: {:?}", cuboid.position().translation.vector.data.0);
    }
}
```
</details>

**Comment by sebcrozet** [comment]
CCD is only enabled when relative velocities of the objects are large enough that they would travel a distance greater than the sum of the collider’s `Shape::ccd_thickness()` (to avoid tunneling). Since the ground is very large, that thickness will be very large too, so CCD won’t be enabled in this example.

I guess there are two things we could do about this:
1. We could use the `min` of the `ccd_thickness()` of both colliders instead of the sum?
2. We could add a coefficient that we would multiply with the `ccd_thickness` so you can let CCD kick-in earlier, even if we know there won’t be any tunneling. That multiplier would either be global to the whole simulation (affecting [that line](https://github.com/dimforge/rapier/blob/master/src/dynamics/ccd/toi_entry.rs#L109)), or could be specific to each collider.

**Comment by Ralith** [comment]
Thanks for having a look! It sounds like this is actually working as intended, then. I expected CCD to forbid interpenetration entirely, rather than only prevent tunneling, which led me to suspect this might be a symptom of more severe misbehavior I've been hunting in my project, but it now sounds unrelated.

> 1. We could use the min of the ccd_thickness() of both colliders instead of the sum?

I think this might would the results less surprising, perhaps even combined with 2 so people can reason about what proportion of an object's approximate size should be allowed to interpenetrate in the worst case.

However, now knowing that the current behavior is intended, it's not actually a problem for me; anti-tunneling is all I really want anyway, and if the current approach gets me better performance for that, great! I just need to keep working on a repro for the real issues I've been hunting. The sideways motion during collision resolution is a bit funny but I'll assume it's inconsequential.

Closing since it's not obvious to me that rapier should actually change anything here, though I might send a doc PR later.
