### ISSUE TITLE
Bug with large moving colliders (0.11.1)

### ISSUE THREAD

**Issue by eldyer** [dimforge/rapier#244]
For frustum culling I'm using a rather large kinematic position based convex hull sensor which moves with the camera.

Now while the frustum sensor is "strafing" left and right (no rotation, everything orthogonal / parallel), it seems to miss non rotated cube shape bodies. This becomes visible as flickering geometry in my app. The problem only occurs in motion of the frustum sensor and disappears as soon as I rotate the frustum OR the cube collider a tiny bit.

I'm not sure when this bug was introduced but it might be related to the fix in 0.11.1 ("Fix a bug causing large moving colliders to miss some collisions after some time.")

**Comment by eldyer** [comment]
Addition: I found out that the bug only occurs when the x/z side of the frustum is exactly a square.

**Comment by sebcrozet** [comment]
Hi! This issue is quite old and doesn’t provide sufficient information for debugging or checking if the bug still exists in the latest Rapier version. So I will close it but feel free to reopen with a test case if you still get a problem.
