### ISSUE TITLE
No proximity or contact detected between moving Kinematic and Static

### ISSUE THREAD

**Issue by vilcans** [dimforge/rapier#25]
I'm moving a Kinematic object and expect to get proximity or contact events when the Kinematic intersects a Static object.

I investigated this more, and found that the results are different depending on whether the moving object is a sensor. But in both cases, no intersection between a Kinematic and a Static is reported.

Here are the results. Note that when a moving Kinematic intersects a Static, the result is None (no contact).

```
Moving object is not a sensor:
Moving Dynamic vs Dynamic => Contact
Moving Static vs Dynamic => None
Moving Kinematic vs Dynamic => None
Moving Dynamic vs Static => Contact
Moving Static vs Static => None
Moving Kinematic vs Static => None
Moving Dynamic vs Kinematic => Contact
Moving Static vs Kinematic => None
Moving Kinematic vs Kinematic => None

Moving object is sensor:
Moving Dynamic vs Dynamic => Proximity
Moving Static vs Dynamic => None
Moving Kinematic vs Dynamic => Proximity
Moving Dynamic vs Static => Proximity
Moving Static vs Static => None
Moving Kinematic vs Static => None
Moving Dynamic vs Kinematic => Proximity
Moving Static vs Kinematic => None
Moving Kinematic vs Kinematic => None
```

Test program here: https://github.com/vilcans/rapier-intersection-test

Please let me know if I have misunderstood how detection is supposed to work.

**Comment by sebcrozet** [comment]
Currently, contacts and proximity are never computed between colliders attached to two static/kinematic bodies. This is being discussed in #15 .

So most of what you are observing are currently the expected behavior, except for:

```
Moving Static vs Dynamic => None (both sensor and non-sensor cases)
Moving Kinematic vs Dynamic => None
```

which look like a bugs.

**Comment by sebcrozet** [comment]
Closing this as all these cases can now be obtained by setting up the appropriate physics hooks.
