### ISSUE TITLE
How can i make it one direction collision-detection?

### ISSUE THREAD

**Issue by szdytom** [dimforge/rapier#256]
i'm working on a 2D game and i want to make the groud that only from up to down the player can be effected by it and stand on it, while when the player is down to up, player can directly go through as if nothing is there.

**Comment by sebcrozet** [comment]
What you are looking for is called a "one-way platform". You can do this by using physics hooks. There is an example [there](https://github.com/dimforge/rapier/blob/master/examples2d/one_way_platforms2.rs).

**Comment by szdytom** [comment]
It works for me now, thx a lot!
