### ISSUE TITLE
panic when run all_examples2 on  MacPro book Apple M1

### ISSUE THREAD

**Issue by simon-fu** [dimforge/rapier#261]
1. repo commit: 8fa66538207cff6db0a840ec8bd08634dc969e13

2. command: cargo run --release --bin all_examples2

3. Error:

wgpu error: Validation Error

Caused by:
    In a RenderPass
      note: encoder = `<CommandBuffer-(1, 2, Metal)>`
    In a pass parameter
      note: command buffer = `<CommandBuffer-(1, 2, Metal)>`
    attachment's sample count 2 is invalid

thread 'main' panicked at 'Handling wgpu errors as fatal by default', /Users/simon/.cargo/.../wgpu-0.7.1/src/backend/direct.rs:1896:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by jsatka** [comment]
This issue shall get fixed when the testbed gets updated to use latest bevy with wgpu-0.12.

**Comment by sebcrozet** [comment]
Fixed in Rapier v0.12.0 (non-alpha version). Please reopen if the problem persists.
