### ISSUE TITLE
[Feature Request] 6DOF Joint

### ISSUE THREAD

**Issue by funmaker** [dimforge/rapier#262]
Hi. Great work on this crate, it came really handy in the projects I'm working on. However the models I'm working on can have more complex types of joints that rapier doesn't support.

Are there any plans for adding 6DOF joints that could be configurable on each translation/rotational axis(fixed/limit/free/spring(?))? Something like Unity's Configurable Joint or PhysX's 6DOF Joint.

Thank you for your work.

**Comment by sebcrozet** [comment]
Hi! As part of my ongoing work on multibodies, I am reworking the way our current joints are implemented in a way that will make it possible to add a 6DOF joint. While the multibodies an the joint rework will be released before the end of the year, the  addition of a 6DOF joint will only happen later next year.

**Comment by sebcrozet** [comment]
All the joints an Rapier are based off a 6-dofs joint now: the [`GenericJoint`](https://docs.rs/bevy_rapier3d/0.19.0/bevy_rapier3d/dynamics/struct.GenericJoint.html).
