### ISSUE TITLE
Feature request: stop_at_penetration flag for linear shape casts

### ISSUE THREAD

**Issue by Ralith** [dimforge/rapier#266]
This might be very useful for character controllers, which tend not to need the additional complexity of a nonlinear cast, but usually spend most of their time moving parallel to surfaces they're in contact with. Currently I'm instead working around the problem by shifting my character controller a cm or so away from any nearby surface, but this requires significant additional code and computation.

**Comment by sebcrozet** [comment]
The `QueryPipeline::cast_shape` has a `stop_at_penetration` flag now in Rapier 0.16.
