### ISSUE TITLE
[Bug?] Collider contacts aren't cleared with another object when CollisionGroups are changed s.t. they cannot interact

### ISSUE THREAD

**Issue by LueptowK** [dimforge/rapier#268]
If two colliders are contacting one another, then one collider's collision groups are changed so they cannot interact, or one object is set to velocity-based kinematic, the contact between the two objects doesn't go away, preventing movement or causing pushing that shouldn't happen, until the two colliders move away from one another.

**Comment by sebcrozet** [comment]
Fixed in Rapier v0.12.0 (non-alpha version). Please reopen if the problem persists.
