### ISSUE TITLE
Demos don't render in firefox

### ISSUE THREAD

**Issue by kikawet** [dimforge/rapier#269]
here I add a screenshot from all the details in the browser while the game is running, I'm using firefox version 95.0.2 64-bit (latest at the moment). 

Since it doesn't show any errors I don't know the source of the problem, but apparently the issue is in the render side since the graph in the top left seems to reflect that something is being simulated.

I tested the same web using edge and works properly.

I suppose this is a bug rather than intended behaviour.

![imagen](https://user-images.githubusercontent.com/28111220/148451699-6c111699-a9b9-46f4-b113-154f1ad7b5df.png)

**Comment by jcyuan** [comment]
implement your own render then, that's just a demo it won't affect anyting, the rendering part of the demo is PIXI, not a module from Dimforge, btw, such issue you should post to rapier.js project not here.

**Comment by kikawet** [comment]
how is this related to rapier.js? if is a rendering problem with PIXI and the demos are in this repo the I think the issue should be in this repo.

But anyway it seems to be fixed already 
![imagen](https://user-images.githubusercontent.com/28111220/149080259-affa6f23-fd31-4f4f-a61c-cc79729956e3.png)
