### ISSUE TITLE
Add geometry::Shape::Plane

### ISSUE THREAD

**Issue by iwikal** [dimforge/rapier#27]
Ncollide3d seems to support it already: https://docs.rs/ncollide3d/0.24.0/ncollide3d/shape/struct.Plane.html

**Comment by iwikal** [comment]
My use-case is that I want to have an infinite, static plane as a simple ground for other objects to sit on. Not sure how a dynamic infinite plane behaves.

**Comment by sebcrozet** [comment]
Planes are not supported because the broad-phase would not know how to handle them right now (because planes have infinite extents). So right now the workaround is to create a `Cuboid` or a `Heighfield` with no subdivision, big enough to cover your scene.
