### ISSUE TITLE
convex_decomposition  3d crash in demos

### ISSUE THREAD

**Issue by MyelinsheathXD** [dimforge/rapier#280]
Hey ! it's keep crashing when I open a "convex_decomposition " scene in  the examples 3D . But other scenes works fine.

I am on PC .

**Comment by sebcrozet** [comment]
Hi! In order to run the `convex_decomposition` demo, you had to be on the `all_examples3d` folder (otherwise it wouldn’t fin the assets). Now that #282 is merged, you should be able to run it properly from the root of the repository `cargo run --release --bin all_examples3`.
