### ISSUE TITLE
Assertion error in `SAPLayer::unregister_subregion`

### ISSUE THREAD

**Issue by finnbear** [dimforge/rapier#281]
I don't have a reproducible example at this time (the issue has happened exactly four times so far). What I can say is that my scene consists of many (50) static cuboid colliders and many (1000) dynamic ball/cuboid colliders, and many colliders get added/removed over time.

The panic occurred shortly after startup, so I doubt a rigid body going out of bounds was the problem.

### Assertion that failed

https://github.com/dimforge/rapier/blob/aaf80bfa872c6f29b248cab8eb5658ab0d73cb4a/src/geometry/broad_phase_multi_sap/sap_layer.rs#L161

### Stack trace (unfortunately, many frames are obfuscated)
```
panicked at 'assertion failed: `(left == right)`
  left: `1047`,
 right: `475`', /home/finnb/.cargo/registry/src/github.com-1ecc6299db9ec823/rapier2d-0.12.0-alpha.1/src/geometry/broad_phase_multi_sap/sap_layer.rs:162:17

Stack:

Error
    at e.wbg.__wbg_new_693216e109162396 (http://localhost:8000/build/bundle.js:1:7096)
    at http://localhost:8000/build/client.wasm:wasm-function[1288]:0xcde87
    at http://localhost:8000/build/client.wasm:wasm-function[630]:0xa3ab6
    at http://localhost:8000/build/client.wasm:wasm-function[981]:0xb0a7e
    at http://localhost:8000/build/client.wasm:wasm-function[436]:0x8c6ef
    at http://localhost:8000/build/client.wasm:wasm-function[791]:0xaa0ff
    at http://localhost:8000/build/client.wasm:wasm-function[177]:0x25e0f
    at http://localhost:8000/build/client.wasm:wasm-function[401]:0x8547e
    at http://localhost:8000/build/client.wasm:wasm-function[1004]:0xc6ec8
    at Object.frame (http://localhost:8000/build/bundle.js:1:21934)
```
Indices from fourth time:
```
panicked at 'assertion failed: `(left == right)`
  left: `77`,
 right: `84`'
```
(no pattern as to whether left > right or left < right)

### Version and features
```toml
rapier2d = {version = "0.12.0-alpha.1", features=["serde-serialize"]}
```
```
rustc 1.58.0-nightly (4e0d3973f 2021-10-27)
```

### Additional context

My application has a client and server, and the server only sends nearby (visible) rigid body updates (custom struct including position, velocity, angular velocity, etc.) to the client, which incorporates this information into its own physics world (by calling methods like `set_position`, `set_linvel`, etc.). The panic occurred on the client (all integration parameters are default except `dt`, no CCD), but not the server.

Visual approximation of world (from 2nd crash). Note that small white dots are not part of the physics world:
![image](https://user-images.githubusercontent.com/20015102/150662170-8687eb3f-17d5-4c51-8e40-8996a9ec7793.png)

**Comment by sebcrozet** [comment]
Fixed in Rapier v0.12.0 (non-alpha version). Please reopen if the problem persists.
