### ISSUE TITLE
When will the new features like 'physx5.0' be supported? such as 'Soft Body Dynamics'、'Cloth'、'PBF'、'...'

### ISSUE THREAD

**Issue by smallverse** [dimforge/rapier#294]
[physx5.0 sdk](https://developer.nvidia.com/physx-sdk) 
[cloth](https://developer.download.nvidia.cn/video/cloth.mp4)
[fire](https://developer.download.nvidia.cn/video/nvidia-physx-fire-720p.mp4)

**Comment by sebcrozet** [comment]
Similar to my answer to #295: soft-bodies, pbf, molecular dynamics are very low-priority right now. So when these features are supported will strongly depend on when/if we get funding for it.

That being said, Material Point Method (MPM) is something we have been working on during the part few months. A first CUDA version of our MPM simulator will be released in April or May this year.

**Comment by smallverse** [comment]
thanks
