### ISSUE TITLE
When will 'GPU' be supported？

### ISSUE THREAD

**Issue by smallverse** [dimforge/rapier#295]
[physics-simulation-with-rapier-2021-roadmap](https://www.dimforge.com/blog/2021/01/01/physics-simulation-with-rapier-2021-roadmap/#rapier-roadmap-for-2021)

**Comment by sebcrozet** [comment]
A GPU version of the physics simulator isn’t planned in a near future (unless we get funding for this specifically). So it will likely not happen this year nor next year. We will reassess the need and financial viability of making a GPU version of Rapier in 2024.

**Comment by smallverse** [comment]
thanks
