### ISSUE TITLE
Add collision exceptions.

### ISSUE THREAD

**Issue by kakoeimon** [dimforge/rapier#3]
Add the ability to add collision exceptions between the two or more rigid bodies.

**Comment by sebcrozet** [comment]
What do you mean exactly by "collision exceptions"? How is this different from #2 from the end-user point of view?

**Comment by dpmkl** [comment]
I would reckon he means something like the collision filter callback in Box2D. https://github.com/erincatto/box2d/blob/master/src/dynamics/b2_world_callbacks.cpp#L28 
This could come in handy for 2D Platformer mechanics, where are able to jump up through platforms but don't fall down through them.

**Comment by kakoeimon** [comment]
The difference is that you may want an object not to collide with a particular object and not the whole group.
For example a bullet will collide with all the objects but not with the player who shooted it.

**Comment by jpetkau** [comment]
Some examples:
* Chain or cloth: allow each link to interpenetrate its neighbors, but collide normally with everything else
* 2D physics: often you want to ignore self-collision (e.g. in a side-view game with a walking character, the character's legs should be able to cross each other).
* (Sort of the same): 2D game with pseudo-depth in Z: objects should be able to pass in front of/behind other layers, but still hit their own layer.

The most general form of this would be an arbitrary predicate saying whether a pair of objects can collide or not. But simple filter bitmasks are faster and useful enough for many cases. Examples:

* In Box2d each object has a 32-bit "category" and a 32-bit "mask", and collisions require `obj1.cat& obj2.mask && obj2.cat & obj1.mask`: http://www.iforce2d.net/b2dtut/collision-filtering
* In NVidia's flex there's a 32-bit "phase", with a 24-bit "group" and a 1-bit "flag" indicating whether a particle should collide with other particles with the same group.

**Comment by kakoeimon** [comment]
It is not a dup of #2 
Think about it as a bullet/granade that can do a frendly fire but cannot damage the shooter/thrower.
This is not just for 2D, neither masks and layers are.
Those two #2 and this are essential in game making. Especialy if there are no plans to expose to the user checks just before the collision detection.
If there are plans to expose to the users a way to make checks before the actual collision detection then there is no need to implement this, neither #2 and the user can implement his own checkings.

**Comment by jpetkau** [comment]
I'm not sure how what you're describing differs from "an arbitrary predicate saying whether a pair of objects can collide or not"?

> It is not a dup of #2 ...
> Think about it as a bullet/granade that can do a friendly fire but cannot damage the shooter/thrower.
> This is not just for 2D, neither masks and layers are.

I wasn't saying it's only for 2D (e.g. the cloth example only makes sense in 3D). I was just giving some examples of when it's useful, and two of them happened to be for 2D.

**Comment by kakoeimon** [comment]
Yes without the "But" It does not differ.

**Comment by sebcrozet** [comment]
Thank you for your feedbacks @kakoeimon  and @dpmkl. So I fink we are talking here about letting the user setup some arbitrary filter rule for collision pairs. I think this is something we will want to add, yes.
We will also need #2 which is more efficient but not as versatile.
