### ISSUE TITLE
Kinematic Character Controller

### ISSUE THREAD

**Issue by lain-dono** [dimforge/rapier#307]
Most wanted feature for games.

From PhysX:  [CharacterControllers](https://docs.nvidia.com/gameworks/content/gameworkslibrary/physx/guide/3.3.4/Manual/CharacterControllers.html), [Vehicles](https://docs.nvidia.com/gameworks/content/gameworkslibrary/physx/guide/3.3.4/Manual/Vehicles.html).

Existing implementations can be ported. However, something similar to #169 is needed.

**Comment by sebcrozet** [comment]
Rapier 0.16 has a character controller now.
