### ISSUE TITLE
Add `sensor` bool to new `CollisionEvent`

### ISSUE THREAD

**Issue by ndarilek** [dimforge/rapier#308]
The new collision handling makes it difficult to detect whether a given collision is with a sensor. Sure it's possible to pull both entities and check whether one is or is not a sensor, but for the case where different handling is needed if a thing collides with a sensor, the new event structure makes determining that more difficult.

I think passing a `bool` as a third member of `CollisionEvent::Started` and `CollisionEvent::Stopped` would be a huge help.

Thanks.

**Comment by sebcrozet** [comment]
A `CollisionEventFlags` has been added to collision events with Rapier 0.12.0 (non-alpha version). These flags can indicate if one of the collider was a sensor.
