### ISSUE TITLE
RigidBodyActivation::cannot_sleep() does not work

### ISSUE THREAD

**Issue by nkzawa** [dimforge/rapier#311]
When it's activated, the struct looks like the following:

```
RigidBodyActivation {
  linear_threshold: -1.0,
  angular_threshold: -1.0,
  time_since_can_sleep: 2.0,
  sleeping: true
}
```

rapier3d, version 0.12.0-alpha.1 (bevy_rapier3d 0.12.1)

**Comment by sebcrozet** [comment]
Fixed in Rapier v0.12.0 (non-alpha version). Please reopen if the problem persists.
