### ISSUE TITLE
Getting started page example is not working

### ISSUE THREAD

**Issue by emadbaqeri** [dimforge/rapier#316]
I had started to read the documentation and used the traditional style of `command + c` to get something up and running :)
But the compiler is blaming about this line
```rust
  let mut joint_set = ImpulseJointSet::new();
```
This is the error I'm getting, 
```bash
failed to resolve: could not find `ImpulseJointSet` in `rapier3d`
could not find `ImpulseJointSet` in `rapier3d`rustc[E0433](https://doc.rust-lang.org/error-index.html#E0433)
```
How am I supposed to call this and get this example up and running.

**Comment by emadbaqeri** [comment]
Hi @sebcrozet, I have no idea about that. because there is no versioning indicator on the website.
But for the code I have also tried to use 
```rust
use rapier3d::dynamics::{ImpulseJoinSet}
```
Which didn't work unfortunately

**Comment by sebcrozet** [comment]
Yeah, the versioning could be made more obvious. The `ImpulseJointSet` doesn’t exist in the version 0.11 (it was named `ImpulseJoint`). So you need to at least switch to 0.12.0-alpha.0.

> Are you having it in the source code but you have not published it or something?

The version 0.12.0-alpha.0 is already published: https://crates.io/crates/rapier3d/versions

**Comment by emadbaqeri** [comment]
thanks for the quick response. It made the situation worse for me. I should first take a look at the source code then try to build something for my self.
You think is there anything that I can help on anything? I background of `javascript` and already trying to learn `rust`

**Comment by sebcrozet** [comment]
> You think is there anything that I can help on anything? I background of javascript and already trying to learn rust

Something that could be interesting is experimenting with writing a character controller or vehicle controller with Rapier.

**Comment by emadbaqeri** [comment]
> > You think is there anything that I can help on anything? I background of javascript and already trying to learn rust
> 
> Something that could be interesting is experimenting with writing a character controller or vehicle controller with Rapier.

Seems interesting and fun thing to do, will give it a try and update you with the outcome.
