### ISSUE TITLE
Shape Cast Does Ignores Collisions With Heightfield

### ISSUE THREAD

**Issue by zicklag** [dimforge/rapier#347]
I have a simple scene that I've built in `bevy_rapier3d`, and after doing some testing it appears that a `cast_shape` will never report intersections with a heightfield. `cast_ray` works, and `cast_shape` will still collide with a cuboid just fine.

Is this expected or is it a bug?

**Comment by sebcrozet** [comment]
This is a known bug. Shape-casting isn’t implemented for heightfields yet. A workaround is use a `TriMesh` instead if shape-casting is required.

**Comment by zicklag** [comment]
I'll try a `TriMesh` then, thanks!

**Comment by sebcrozet** [comment]
Linear shape-casting on heightfields work now in Rapier 0.16.
