### ISSUE TITLE
The pleural of "axis" is "axes", and not "axii"

### ISSUE THREAD

**Issue by robert-hrusecky** [dimforge/rapier#36]
Sorry if I'm being too pedantic, but this was really starting to get on my nerves while reading the code. The fix should be as simple as doing a find-and-replace. Unless there's some other obscure reason for using the term "axii"?

**Comment by sebcrozet** [comment]
Well until now brain told me the plural of axis was `axii`, probably because I leaned a while ago that one the plurals of `radius` is `radii`. So my non-native English mind tried to generalize too much with `axis`.

TIL it should be `axes`, thanks!

**Comment by UgurcanAkkok** [comment]
A quick `rg axii` and `rg --no-ignore axii` doesnt return any results while `rg axes` does return some results. I guess this issue is now deprecated/solved already.

**Comment by sebcrozet** [comment]
@UgurcanAkkok Thanks! Yes, I solved it in the last release and forgot to close this issue.
