### ISSUE TITLE
Regression in performance?

### ISSUE THREAD

**Issue by iMplode-nZ** [dimforge/rapier#37]
![image](https://user-images.githubusercontent.com/31631663/96031011-a0351b80-0e11-11eb-8d48-497cf2a09747.png)

This is the chart on the website. It seems that Rapier has lost 5ms over where it was at 2020-09-13, and now it is slower than PhysX.

**Comment by sebcrozet** [comment]
This is not a regression in performance. This was a change of hardware for the benchmark server (a downgrade from an AMD Ryzen 9 to an old Intel Core i7). You will see that the more recent benchmark for at the same commit `benchbot@0829ed1` 2020/09/26 (you selected the one from 2020/09/13) ran after the change of CPU show the same performances as `refs/heads/master@`:

![image](https://user-images.githubusercontent.com/1734958/96032444-f4b2b800-0e5e-11eb-92d3-c55e27b2bcf3.png)
