### ISSUE TITLE
Error in an example about Shape-casting

### ISSUE THREAD

**Issue by Pietrek14** [dimforge/rapier#388]
This is a small error, but in the [user guide about Scene queries](https://rapier.rs/docs/user_guides/bevy_plugin/scene_queries), specifically in the 2d example for shape-casting, ```cast_shape``` is called on ```query_pipeline```, but this is the name from the Rust user guide, the Bevy guide uses the name ```rapier_context```.

**Comment by sebcrozet** [comment]
Thanks for pointing this out. It’s fixed now.
