### ISSUE TITLE
Best way to simulate 2d top down fluid environment ?

### ISSUE THREAD

**Issue by loicbourgois** [dimforge/rapier#39]
Hi, thank you for this lib,

In the example at [basic-setup](https://rapier.rs/docs/user_guides/rust/rigid_body_simulation#basic-setup) I see there's an easy way to specify gravity.

I'm interested in simulating a top down 2d world, with a water like environment. Something a bit like this: [youtube example](https://www.youtube.com/watch?v=JJYpHfccnwA).

What would be the best way to do that ? 

Options :
- use an existing global `drag` parameter, similar to how `gravity` works ; 
- add a new `drag` parameter through an PR, and then use it ; 
  where should I start looking if I want to add such a feature ? 
- manually add a drag force on each body, as drag is not planned in this lib ;
- use another lib compatible with rapier that can handle this ; 
- something else ? 

thanks for your time

**Comment by sebcrozet** [comment]
Closing this issue as it is quite old now. The current version of rapier would probably handle these properly with a combination of damping and spring joints.
