### ISSUE TITLE
Scaling RigidBodies

### ISSUE THREAD

**Issue by hpatjens** [dimforge/rapier#391]
As far as I can see there is no way of scaling a `RigidBody`. Do you indent to add one in the future and is there a workaround?

I think ideally `position` of `RigidBody` and `RigidBodyBuilder` would be `Affine`s instead of `Isometry`s. Isn't that the case because it would add unreasonable complexity to the acceleration structure generation and maintenance?

**Comment by sebcrozet** [comment]
Scaling a rigid-body doesn’t really make sense. A rigid-body is just a point in space.

What you’d want to scale are the colliders, which you can by modifying the collider’s shape to their scaled version. Having this scaling factor directly in the collider’s transform would be too complex and computationally expensive compared to just replace the collider’s shape with its scaled version.
