### ISSUE TITLE
Allow to filter groups in `DebugRenderPipeline`

### ISSUE THREAD

**Issue by GuillaumeGomez** [dimforge/rapier#398]
Currently, it's only possible to filter what kind of item we want to display, but not filter by group. Here is my use case, I have two groups: `OUTSIDE_WORLD` and `INSIDE`. So when I'm entering the `INSIDE` state, I don't want the items from the `OUTSIDE_WORLD` group to be displayed (but I don't remove them as it would take too much time to re-pop them, I only do it for `INSIDE` elements).

Do you think such a feature could be added?

Also: thanks a lot for your crates, they're really incredible to use!

PS: If you think it's a nice feature to add, I can take a look at adding it myself if you want?

**Comment by sebcrozet** [comment]
Hi! Sorry for the late answer. When using the `DebugRenderPipeline`, you have to provide a `DebugRenderBackend` implementation. I think we should add a predicate to that trait to apply custom filtering rules based on the objects that is being rendered.
