### ISSUE TITLE
Example integration with Bevy 

### ISSUE THREAD

**Issue by masonk** [dimforge/rapier#40]
Hi. I'm interested in using the bevy_rapier2d plugin in a new project. I know the integration is early days, but it would be nice to see a simple example of a full integration.

The place where I'm stuck at the moment is how to query for, and update, my RigidBody using a bevy query. Specifically, I'd like to add velocity to my player character while the player presses an arrow key. Something like driving a cube around the screen would be a nice tutorial here.

**Comment by masonk** [comment]
For anyone having a similar issue, I found an example `src` that's using Rapier + Bevy [1]

That's probably enough for me to go on, but I still think it'd be nice to have an example here in this repo - mainly so I'd be assured that the patterns I'm using are the ones intended by the Rapier authors.

[1] https://github.com/Bobox214/Kataster/blob/master/src/player.rs

**Comment by sebcrozet** [comment]
Integration with Bevy is available through the [bevy_rapier2d](https://crates.io/crates/bevy_rapier2d) and [bevy_rapier3d](https://crates.io/crates/bevy_rapier3d) crates.
