### ISSUE TITLE
Trimesh internal edges cause incorrect simulation

### ISSUE THREAD

**Issue by HexaField** [dimforge/rapier#404]
Ball colliders seem to be affected by trimesh internal edges, rolling at odd angles and along edges.

**Comment by ottoville** [comment]
This must be duplicate of https://github.com/dimforge/rapier/issues/372
I think this is a major issue, making trimesh very hard to use in projects.

**Comment by HexaField** [comment]
> This must be duplicate of #372 I think this is a major issue, making trimesh unusable.

This is not the same issue. Your issue is due to rolling friction not being implemented yet, this issue is to do with a bug in triangle mesh triangulation.

**Comment by ottoville** [comment]
> > This must be duplicate of #372 I think this is a major issue, making trimesh unusable.
> 
> This is not the same issue. Your issue is due to rolling friction not being implemented yet, this issue is to do with a bug in triangle mesh triangulation.

I see, so these two issues together results chaotic behavior of rolling shapes with triangle mesh.

**Comment by sebcrozet** [comment]
This will be addressed (for the 3D version of Rapier) by https://github.com/dimforge/parry/pull/101.

**Comment by sebcrozet** [comment]
This was addressed and released in Rapier 0.16
