### ISSUE TITLE
Collision detection without rigid bodies

### ISSUE THREAD

**Issue by FilipPiktiv** [dimforge/rapier#407]
How would I go about utilizing only the collision detection part? I don't need any collision solving
I basically just want colliders that I can move around, and react to intersections.

Can I make this example work without rigidBodies?

`
    const world = new RAPIER.World({x: 0, y: 0});

    const colliderDescA = RAPIER.ColliderDesc.ball(1000)
      .setSensor(true)
      .setTranslation(100, 100);

    const a: RAPIER.Collider = world.createCollider(colliderDescA);

    const colliderDescB = RAPIER.ColliderDesc.ball(1000)
      .setSensor(true)
      .setTranslation(300, 100);

    const b: RAPIER.Collider = world.createCollider(colliderDescB);

    world.step();

    let intersections = world.intersectionPair(a, b);
    // Logs false
    console.log(intersections);
`

**Comment by sebcrozet** [comment]
Hi! By default, collision-detection is disable between two colliders unless at least one of them is attached to a dynamic rigid-body. You can enable it explicitly by setting the colliders’ [active collision types](https://rapier.rs/docs/user_guides/rust/colliders#active-collision-types) to `ActiveCollisionTypes::all()` (though technically, you only need `ActiveCollisionTypes::FIXED_FIXED`).

**Comment by amoffat** [comment]
I'm still seeing this issue in javascript:

```typescript
const c1 = world.createCollider(
  RAPIER.ColliderDesc.ball(1000)
    .setTranslation(100, 100)
    .setSensor(true)
    .setActiveCollisionTypes(RAPIER.ActiveCollisionTypes.ALL)
);
const c2 = world.createCollider(
  RAPIER.ColliderDesc.ball(1000)
    .setTranslation(100, 100)
    .setSensor(true)
    .setActiveCollisionTypes(RAPIER.ActiveCollisionTypes.ALL)
);
world.step();
console.log(world.intersectionPair(c1, c2)); // false
```

What am I missing?
