### ISSUE TITLE
Documentation outdated 

### ISSUE THREAD

**Issue by OriginLive** [dimforge/rapier#408]
Hi, in https://rapier.rs/docs/user_guides/bevy_plugin/rigid_bodies/#mass-properties

The examples do not work, as `MassProperties` definitely doesn't implement Component in the latest version.
I guess there should be unit tests on the code that's in documentation atleast, so that you know it compiles.

![image](https://user-images.githubusercontent.com/24319526/197304498-2d6d101e-e0fa-472d-9d43-98a82e246c4d.png)

**Comment by gyzerok** [comment]
Do you happen to know what should be used instead?

**Comment by sebcrozet** [comment]
The docs is now updated. The correct component is [`AdditionalMassProperties`](https://docs.rs/bevy_rapier3d/0.19.0/bevy_rapier3d/dynamics/enum.AdditionalMassProperties.html).
