### ISSUE TITLE
rapier3d convex hull regression from 0.15 to 0.16

### ISSUE THREAD

**Issue by LPGhatguy** [dimforge/rapier#417]
Hello! We recently upgraded from rapier3d 0.15 to 0.16. We use rapier's built-in convex hull generation on some of our meshes to get a decent default collision mesh.

We have a few test scenes with dynamic bodies. One of them is a series of barrels sitting on tables that the player can shoot at. The barrel colliders are using convex hull colliders, generated by feeding all of the model's vertices into `ColliderBuilder::convex_hull`.

In rapier3d 0.15.0, those barrels sit on the table and are stable:

https://user-images.githubusercontent.com/654598/201042918-faf714a5-dcf0-45d0-a5c4-a0f08af1d52a.mp4

When upgrading to rapier3d 0.16.0, the barrels roll off of the table when the simulation starts:

https://user-images.githubusercontent.com/654598/201043036-41fe0c8b-40db-4ef6-9ea4-240b5aae3509.mp4

The model is one of Kenney's free assets. Here is a zip file containing the glTF 2.0 file we load: [barrel.zip](https://github.com/dimforge/rapier/files/9978964/barrel.zip).

The collisions generated from this model weren't perfect in 0.15.0, but they have regressed in 0.16.0. I understand that the data that I'm giving rapier may not be great. Using convex decomposition instead results in much better collisions but takes a long time. Is there anything else I can submit to help diagnose this issue?

**Comment by LPGhatguy** [comment]
Hey! Yeah, I think I could probably do that. How do I do that? I've been putting off building our own physics visualization, but if there's something built-in, that sounds great!

**Comment by sebcrozet** [comment]
First, you need to implement the [`DebugRenderBackend` trait](https://docs.rs/rapier3d/latest/rapier3d/pipeline/trait.DebugRenderBackend.html). All that is required is to be able to render a colored line. Then you can create a [`DebugRenderPipeline`](https://docs.rs/rapier3d/latest/rapier3d/pipeline/struct.DebugRenderPipeline.html) and call its [`render` method](https://docs.rs/rapier3d/latest/rapier3d/pipeline/struct.DebugRenderPipeline.html#method.render) at each frame.

**Comment by LPGhatguy** [comment]
Wow, that debug renderer interface is amazing, I wish I had integrated it sooner!

Here is rapier3d 0.15.0: https://i.eryn.io/2246/rapier3d-0.15.0-debug.mp4

Here is rapier3d 0.16.1: https://i.eryn.io/2246/rapier3d-0.16.1-debug.mp4

**Comment by rfurlan** [comment]
I believe I have another example of this issue.  A mesh associated with a convex hull collision proxy is dropped a few units above a plane and comes to rest atop of it on 0.15.0:

![image](https://user-images.githubusercontent.com/115668/202299726-278ba472-4101-4110-a977-c579276f77ca.png)

However on 0.16 and up, it behaves differently after initial contact with the plane.

1 frame after contact:
![image](https://user-images.githubusercontent.com/115668/202300236-70abfff9-bdf2-4913-a8fa-c00a3d01b963.png)

5 frames after contact:
![image](https://user-images.githubusercontent.com/115668/202300320-b650498e-59eb-4eae-bb13-a87428b63555.png)

10 frames after contact:
![image](https://user-images.githubusercontent.com/115668/202300421-27da620f-cf1b-410b-bb9c-9d350fd8a2d7.png)

15 frames after contact:
![image](https://user-images.githubusercontent.com/115668/202300524-13bb4246-2c37-4b35-a504-c991516be3c6.png)

On frame 16, the remaining visible portion of mesh associated with the rigid body instantly tunnels through the plane:
![image](https://user-images.githubusercontent.com/115668/202300616-bd453d81-cb1f-4d28-9c27-02b11d7b619f.png)

**Comment by rfurlan** [comment]
The convex hull itself was generated correctly:

![image](https://user-images.githubusercontent.com/115668/202872516-dc334cd6-2c9e-46b2-8fce-fe935407d689.png)

**Comment by sebcrozet** [comment]
@LPGhatguy, @rfurlan Thank you both for the additional details. Could you please add the following to your `Cargo.toml` and see if that fixes the regression you are observing ?

```toml
[patch.crates-io]
parry3d = { git = "https://github.com/dimforge/parry", branch = "odd-convex" }
```

**Comment by rfurlan** [comment]
@sebcrozet yes everything behaves as expected with the patch, thank you :)

![image](https://user-images.githubusercontent.com/115668/211386385-b869f138-0f2e-435e-8382-4cee57ee4b89.png)
