### ISSUE TITLE
Feature Request: C++ binding of rapier2d-compat and rapier3d-compat

### ISSUE THREAD

**Issue by 8Observer8** [dimforge/rapier#444]
I really hope that this will be possible in the future. I want to use it with MinGW.

**Comment by APerricone** [comment]
This issue leads to field "rust/c++ interoperability", I am interested too. I don't have time to try, but a think the road is something like the one explained here: [How to create C binding for a Rust library](https://developers.redhat.com/articles/2022/09/05/how-create-c-binding-rust-library).

**Comment by sebcrozet** [comment]
Writing C/C++ bindings for Rapier sounds possible, but that’s a significant endeavor that will not happen without community contributions or significant funding.

I’ll keep this open, but mark this as `wontfix` for now.
