### ISSUE TITLE
doc character_controller bug query

### ISSUE THREAD

**Issue by Lightnet** [dimforge/rapier#452]
Found a bug in code set up for https://rapier.rs/docs/user_guides/bevy_plugin/character_controller/

```
fn read_result_system(controllers: Query<Entity, &KinematicCharacterControllerOutput>) {
```

```
fn read_result_system(controllers: Query<(Entity, &KinematicCharacterControllerOutput)>) {
```
Had to look at the bevy doc a bit how to learn to get the correct return values.

Bevy Engine 0.9.1

bevy_rapier3d 0.20.0

**Comment by sebcrozet** [comment]
Thank you for pointing this out. The typo is fixed now.
