### ISSUE TITLE
Getting started page code is outdated

### ISSUE THREAD

**Issue by frederickjjoubert** [dimforge/rapier#459]
On the [getting started page](https://rapier.rs/docs/user_guides/bevy_plugin/getting_started_bevy) for rapier_2d the example code

```rust
[dependencies]
# TODO: Replace the * by the latest version numbers.
bevy = "*"
bevy_rapier2d = { version = "*", features = [ "simd-stable", "debug-render" ] }
```

is wrong / out of date.

It needs to be 

```rust
[dependencies]
# TODO: Replace the * by the latest version numbers.
bevy = "*"
bevy_rapier2d = { version = "*", features = [ "simd-stable", "debug-render-2d" ] }
```

or you will get the `error: failed to select a version for "bevy_rapier2d"` error.

See https://discord.com/channels/507548572338880513/748627261384556715/1080610679184183326

**Comment by akappel** [comment]
I actually created a PR for this a couple weeks ago; still waiting for the thumbs up: https://github.com/dimforge/rapier.rs/pull/58

**Comment by sebcrozet** [comment]
Closing this since https://github.com/dimforge/rapier.rs/pull/58 is merged both. Thank you both!
