### ISSUE TITLE
Accessing Segment/Polygon Collider data

### ISSUE THREAD

**Issue by ElnuDev** [dimforge/rapier#46]
What's the deal with the [`Segment`](https://docs.rs/rapier2d/0.3.0/rapier2d/geometry/enum.ShapeType.html#variant.Segment) and [`Polygon`](https://docs.rs/rapier2d/0.3.0/rapier2d/geometry/enum.ShapeType.html#variant.Polygon) variants of [`rapier2d::geometry::ShapeType`](https://docs.rs/rapier2d/0.3.0/rapier2d/geometry/enum.ShapeType.html)? All the other variants have corresponding [`rapier2d::geometry::Shape.as_xxx`](https://docs.rs/rapier2d/0.3.0/rapier2d/geometry/trait.Shape.html#impl-1) functions that let you get data on them.
How is one supposed to get data from segment and polygon colliders? Are they special cases? Thanks in advance!

**Comment by sebcrozet** [comment]
The segment and polygon shapes are not very well supported by Rapier yet. Most of the collision-detection algorithm are not implemented yet so you won’t get very far with them. That being said, you can use `collider.shape().downcast_ref::<Segment>()` for downcasting the shape to a segment, if it is one (the same can be used for any shape type and all the `as_xxx` methods are just calling this downcast function internally).

**Comment by ElnuDev** [comment]
Alright, thanks! That worked. So I'm guessing the `as_xxx` methods for segments and lines will be added once they're are more fleshed out and ready for use? I am writing a system for `ggez` that draws debug for `rapier2d`'s colliders, so I wanted to include all of the types for completeness.
