### ISSUE TITLE
KinematicCharacterController min_slope_slide_angle does not send any information to output when slope angle is larger than min_slope_slide_angle

### ISSUE THREAD

**Issue by Jeff425** [dimforge/rapier#465]
Why is this an issue?
The KinematicCharacterController has a field min_slope_slide_angle that when set, it should make entities that are on steeper slopes to slide down. While the handle_slopes function here https://github.com/dimforge/rapier/blob/c85a833d3a2e4c66024627a9745f033fbbee283a/src/control/character_controller.rs#L475
does do that, it does not send any information to the consumer that it is sliding down a slope. As a consumer, there needs to be a way to know if an entity is currently sliding down a slope in order to maintain things like gravity acceleration.

Potential fix:
Add an extra boolean flag such as `is_sliding_down_slope` to the KinematicCharacterControllerOutput when https://github.com/dimforge/rapier/blob/c85a833d3a2e4c66024627a9745f033fbbee283a/src/control/character_controller.rs#L498 is reached.

**Comment by sebcrozet** [comment]
I don’t think we should change the meaning of the `grounded` flag to add some special-case. Instead, we could add another flag `is_sliding_down_slope` that would be set to `true` in the case you are describing.

**Comment by Jeff425** [comment]
Oh yeah that works as a more generic solution. I'll update the issue
