### ISSUE TITLE
Add optional bevy feature for reflection

### ISSUE THREAD

**Issue by janhohenheim** [dimforge/rapier#467]
Currently, `bevy_rapier` can (de facto) not be used in tandem with bevy dynamic scenes, since colliders cannot be serialized due to not being `Reflect`. This means that save systems that would like to use the built-in bevy scene format need to clutter the graph with marker traits for which colliders were spawned how, which defeats the purpose of the dynamic scene as "just dump the entire world into a file and don't worry about it". Additionally, colliders cannot be inspected at runtime in editors, which is a pity if generating them dynamically.

I propose adding an optional `bevy_reflect` feature to rapier that only derives `Reflect` and `FromReflect` for the types that aren't in `bevy_rapier` and then add them to the type registry through `bevy_rapier`.

If I get your okay @sebcrozet, I'll do this myself.

**Comment by sebcrozet** [comment]
Could `Reflect` just be implemented directly (manually) on the wrapper types defined by `bevy_rapier` instead of having to be propagated down to `rapier` (and, most likely, `parry`)?

**Comment by sebcrozet** [comment]
There is no plan to add a `Reflect` derive to `rapier` since that would also require such feature on `parry`, and `nalgebra`. We should  have `Reflect` implemented manually in `bevy_rapier` types instead.

**Comment by janhohenheim** [comment]
Last time I checked (1 year ago), this was impossible to do properly as the underlying types inside the wrappers did not derive `Reflect`. There is a PR in the works in Bevy that allows deriving `Reflect` on foreign types by redefining them and then deriving `Reflect` on these dummy types. You can do that, just be aware that this means duplicating many `parry` types for `bevy_rapier`.

**Comment by sebcrozet** [comment]
Thank you for the info! We’ll keep an eye on this. Hopefully we can work something out at the `bevy_rapier` level eventually.
