### ISSUE TITLE
hey, is there a way to use Rapier without rayon ?

### ISSUE THREAD

**Issue by Kiddinglife** [dimforge/rapier#494]
Hey, my game server is built up on the basis of Tokio async runtime. 
so I want to call rapier api via the threads in the runtime instead of Rayon.
Is it easy to let the api user decide the threading model of rapier collision apis ?
Thank you very much !

**Comment by sebcrozet** [comment]
Hi! It is not possible to switch to a threading model other than rayon when multi-threading is enabled for rapier. `async` is generally not considered suited for compute-heavy tasks where rayon’s work-stealing scheduler is more suited.

**Comment by Kiddinglife** [comment]
hey mate, my game dev is in and cpu heavy app at the same time. No good trade off for me. Either losing asynchrony support or losing rayon support. I chose losing rayon and do the dirty jobs of parallel myself. Anyway close now.
