### ISSUE TITLE
What is wrt?

### ISSUE THREAD

**Issue by kantum** [dimforge/rapier#498]
Hi,

I'm following the tutorial, and you're referring to the rigid-body `wrt`. 

I have no idea what it is, and a quick search on Google gives me answers not related to either gaming nor physics.

**Comment by sebcrozet** [comment]
Hi! It’s the common acronym for "With Regard To".

**Comment by kantum** [comment]
WIth regard to what?

I'm no aware of a kind of construct that would put the subject before "to".

Here the usage I found in the doc:
<img width="552" alt="image" src="https://github.com/dimforge/rapier/assets/43590963/dcb85487-0986-4c0d-921f-39a49645deec">


Here a list of example [from collins](https://www.collinsdictionary.com/sentences/english/with-regard-to):
<img width="743" alt="image" src="https://github.com/dimforge/rapier/assets/43590963/f72c692d-523f-491b-ba8d-515e22009065">

**Comment by sebcrozet** [comment]
Resistance of the body with regard to linear movement. It sounds similar to the example "Her inferiority complex with regard to Royal [...]".

**Comment by kantum** [comment]
OK, I still think it is confusing, but I get it, the dot in "wrt." is not ending the sentence.

Thanks, I'll be able to understand this part now 😅

**Comment by sebcrozet** [comment]
Oh, I see! Mmh, we usually do this for abbreviations in French, perhaps it’s not that common in English and we should remove that dot.

**Comment by kantum** [comment]
To be honest, I think avoiding abbreviation all together is a good option for documentation.
