### ISSUE TITLE
Typo in Docs for moving the Collider's Transform (bevy_rapier3d)

### ISSUE THREAD

**Issue by alphastrata** [dimforge/rapier#503]
is: 
```rust
/* Set the collider position inside of a system. */
fn modify_collider_position(mut positions: Query<&mut Transform, With<Collider>) { // <<<<MISSING A CLOSING ANGLE BRACKET
    for mut position in positions.iter_mut() {
        position.translation.x = 2.0;
    }
}
```
should be :
```rust
fn modify_collider_position(mut colliders: Query<&mut Transform, With<Collider>>) {
    for mut position in colliders.iter_mut() {
        position.translation.x = 2.0;
    }
}
```
![image](https://github.com/dimforge/rapier/assets/25101888/798d4306-fd4d-4487-8453-649f94b24cd1)
missing closing > bracket.

Cannot see how to file a PR directly for those docs so @dimforge folk.

**Comment by sebcrozet** [comment]
Thank you for pointing this out. This is fixed now. PRs affecting the website can target the website’s repository: https://github.com/dimforge/rapier/pull/579
