### ISSUE TITLE
 Add serde derives for KinematicCharacterController

### ISSUE THREAD

**Issue by PaulL48** [dimforge/rapier#506]
KinematicCharacterController appears to be a good candidate to be Serialize/Deserialize. This would require adding serde derives for the following structs.

- CharacterLength
- CharacterAutostep
- KinematicCharacterController

**Comment by PaulL48** [comment]
I've got the changes tested and ready for a PR. I rarely contribute to OS projects so I just wanted to follow the guideline and create an issue to be assured that everything is OK before creating the PR.

**Comment by sebcrozet** [comment]
The corresponding PR https://github.com/dimforge/rapier/pull/508 was merged a while ago. We can close this.
