### ISSUE TITLE
Documentation for understanding physic engines

### ISSUE THREAD

**Issue by Santiago-Torres14** [dimforge/rapier#507]
Hey everyone, I'm Santiago and it's my first time looking at a physics engine. I'd like to understand the project but I lack many of the math  (I know what a vector is, basic operations such as dot and cross product) and geometry knowledge. If somebody could point me in the right direction to be able to understand the rapier library and in general how physics engines work, that'd be cool

**Comment by lucasmaffazioli** [comment]
ChatGPT and Gemini can be great for studying these kind of topics, I'm learning a bunch with their help.
Also take a look at these:
https://www.youtube.com/watch?v=DPfxjQ6sqrc
https://www.youtube.com/watch?v=3lBYVSplAuo

**Comment by sebcrozet** [comment]
Hey! Browsing the bullet physics forum is often very interesting, as well as checking out the work from Erin Catto (author of Box2D).
