### ISSUE TITLE
narrow_phase::contacts_with giving wrong contact

### ISSUE THREAD

**Issue by cybersoulK** [dimforge/rapier#526]
I have a rotated cube at 45 degrees (Dynamic or Fixed). 
I have other objects detect a contact on the empty part of the cube. (as if the rotation was none)

The Rigid body physics play out normally, so it's not my mistake with setting up the rotation.
I use the following to build the rigid bodies:
```rust
let rigid_body_handle = self.rigid_body_set.insert(rigid_body_builder);
let collider_handle = self.collider_set.insert_with_parent(collider_builder, rigid_body_handle, &mut self.rigid_body_set);
```

**Comment by sebcrozet** [comment]
Note that `NarrowPhase::contacts_with` will return all the potential contacts (i.e. the pairs of colliders with intersecting AABBs). You need to inspect the `ContactPair::has_any_active_contacts` to check if there is an actual contact. I will rename `NarrowPhase::contacts_with` to `NarrowPhase::contact_pairs_with` in the next release, and add more details to the documentation.
