### ISSUE TITLE
Debug renderer: does not contain mesh data for shapeCasts

### ISSUE THREAD

**Issue by GregorAltstaedt** [dimforge/rapier#536]
Hello Dimforge Team,

The debug renderer is very valuable but sadly shapeCasts (I think raycasts as well) are nor yet included in the world.debugRender() as far as i can see.

Is this correct, or am I missing something?

Thank you in advance

**Comment by sebcrozet** [comment]
This is correct. The debug-renderer reflects the instantaneous state of the simulation. A shape-cast is a one-time geometric query, so it does not "exist" in the physics world as a permanent "object". So, it is out of the scope of the debug-renderer since it isn’t part of the physics world state.
