### ISSUE TITLE
Can testbed visualize coordinate systems?

### ISSUE THREAD

**Issue by alexgoto** [dimforge/rapier#539]
Can testbed visualize coordinate systems? 

As a reference from unreal
https://www.techarthub.com/wp-content/uploads/ue4-axis-example.webp

**Comment by sebcrozet** [comment]
The testbed is mainly designed for testing, and showcasing Rapier features. It is not intended to provide rendering features for other usages.
That being said, the debug-renderer will display the local coordinate systems of each rigid-body. But that doesn’t look anywhere as good as in the picture you linked (it just renders three thin links).
