### ISSUE TITLE
Sensor collider changes physics simulation

### ISSUE THREAD

**Issue by Danvil** [dimforge/rapier#545]
When I add a collider to a rigid body with `.sensor(true)` the rigid body seems to move differently. From the documentation it sounds like sensor colliders do not create contact forces and thus cannot change the position/velocity of a rigid body.

Unfortunately it is a bit difficult to extract a minimal reproducible example, so I first wanted to confirm that adding sensor colliders to a rigid body should not change the outcome of the physics simulation, and if it does then it would be a bug. Could someone confirm that is the case?

On a side note I am also slightly confused by the [documentation on Colliders](https://rapier.rs/docs/user_guides/rust/colliders). The example seems to create a sensor collider but also set density and friction. Why would a sensor collider have a mass and friction?

If this is somehow intended and I am missing something: How can I create a collider which is checked for collisions with other "solid" colliders, but does not change the physics (i.e. no mass/friction/forces)? My use case is to attach a "sensor" to an actor and when another body enters the collider of the sensor I want to react to it.

**Comment by gsteinLTU** [comment]
I'm guessing the `.sensor(true)` part of that example is just for completeness of collider options (same reason they make and then immediately discard a bunch of colliders before it). Friction definitely shouldn't apply. My current project uses sensors and as far as I can tell they do not change the physics significantly. E.g. I have a robot with a sensor on the front, making that sensor bigger doesn't change how the robot handles.

Do the differences you have change if you make the sensor colliders significantly larger/smaller, or if you set the other properties different?

**Comment by gsteinLTU** [comment]
I just tested specifically increasing the mass/density as well (before I was assuming making one of my sensors 100x larger would be noticeable with only the default density, and it wasn't, but a mass of 10000 and my robot falls flat on its face), and I can confirm this is happening too. It feels unintended, although it would allow for making weird center of masses if desired.

**Comment by sebcrozet** [comment]
There was a time when `rapier` sensors did not contributing to the rigid-body’s mass. However users complained about this behavior as it was not symmetric with non-sensor colliders, and would therefore not handle switching between sensors and non-sensors gracefully.
I think this is one of these case where different users expect different behaviors depending on their use-cases.
