### ISSUE TITLE
Debug renderer does not show the current position of the kinematic rigid body

### ISSUE THREAD

**Issue by hakolao** [dimforge/rapier#551]
It seems that the debug renderer doesn't show the current position of the kinematic rigid body:

![image](https://github.com/dimforge/rapier/assets/12234005/b3b4a7eb-a1c0-424f-b156-f96b8762577f)

I'm assuming somehow the `let com = rb.mprops.world_com` doesn't get updated which is used in the `render_rigid_bodies`.

**Comment by sebcrozet** [comment]
This was fixed by #527.
