### ISSUE TITLE
Aabb type is not properly re-exported from Parry

### ISSUE THREAD

**Issue by kvark** [dimforge/rapier#574]
Looks like we are re-exporting the type - https://docs.rs/rapier3d/latest/rapier3d/geometry/type.Aabb.html
But we aren't doing the same for traits implemented by the type, most importantly - https://docs.rs/parry3d/0.13.1/parry3d/bounding_volume/struct.Aabb.html#impl-BoundingVolume-for-Aabb

This limitation makes it impossible to use the `Aabb` type without also depending on Parry3d explicitly.

**Comment by sebcrozet** [comment]
Good point, I will add the re-exports. Note that `rapier` re-exports `parry` as `rapier3d::parry` so an explicit dependency to `parry3d` should already not be necessary.
