### ISSUE TITLE
Site link dead

### ISSUE THREAD

**Issue by MatsJKUL** [dimforge/rapier#576]
The link to the QueryPipeline in the second sentence on this page: https://rapier.rs/docs/user_guides/rust/scene_queries/ is dead. This is the clickable link which is dead: https://rapier.rs/docs/user_guides/rust/scene_queries/simulation_structures#query-pipeline

I'm sorry If this is not an acceptable git issue.

**Comment by MatsJKUL** [comment]
Is the site open source since I don't really think it's in this repo so not sure if it is appropriate to post here?

**Comment by sebcrozet** [comment]
Hi! Thank you for pointing this out. The website is open-source there: https://github.com/dimforge/rapier.rs

**Comment by Vrixyz** [comment]
Closing in favor of https://github.com/dimforge/rapier.rs/issues/41 ; thanks!
