### ISSUE TITLE
Particle physics

### ISSUE THREAD

**Issue by phisn** [dimforge/rapier#588]
I am using rapier in my game as the physics library. My game does contain particles. Since I need determinism and want to simulate without particles I am currently creating a custom physics world for the particles. Particles do not interact with each other. I am currently using bevy but since my particle simulation is separated from the bevy plugin I need a native Rapier solution.

The problem is that when having a lot of rigid bodies that all do not interact with each other they still perform unnecessary computation. I am sure about that because with around 500 circle rigid bodies they contribute to around 70% of all computation in my game (determined using a profiler). 

Is it possible to have a large amount of rigid bodies that all do not interact with each other in a performant way (for example a filter in the broad phase)?

**Comment by sebcrozet** [comment]
Are you compiling in release mode? This makes a massive difference performancewise.
Would you mind posting a screenshot of one of the scenarios causing performances issues? That will help understand what could be going wrong.

**Comment by phisn** [comment]
So. I am currently in progress in porting the application from typescript-rapier to bevy-rapier. I didn't got to implement particles in bevy yet. Therefore I am sure, that rapier is compiled in release mode with this issue. I also know that all performance issue stem from rapier, since this 70% number comes all from the single `.step` call from inside the rapier particle physics. 

Im not sure what you mean by posting a screenshot of the scenario. In my case its a rocket game where I am using particles to model the rockets outcoming thrust. These can reach up to 500 at a time depending on the settings. 

The current runnable code for my particle system is here [repo](https://github.com/phisn/rocket-game/tree/main/packages/web/src/game/runtime-extension/particle). One thing that just came to my mind is to reuse rigidbodies and colliders. But I think I tried that without making any meaningful difference which is why I am currently using the simpler method of creating new ones.

**Comment by sebcrozet** [comment]
Thank you for the repo link. By screenshot I meant something like this:
![image](https://github.com/dimforge/rapier/assets/1734958/12aec15f-785d-4220-9627-7b7107ca0a64)

I wouldn’t advise to use a physics engine for these kinds of particles effect. A simple straight-line or pseudo-random trajectory for these particles would likely be sufficient and way less computationally expensive.

My guess here is that most of the computation times are caused by the fact particles are all spawned intersecting each other, that will cause a significant computation times in the broad-phase (since we effectively have `O(n²)` collisions).

**Comment by phisn** [comment]
Is there any way to prevent the computation in the broad-phase? Or is there any other physics library that would be better suited? (I especially do not need determinism for this feature). It would be interesting if there exists a physics abstraction similar to what unity uses for particles. There it rasterises the whole world and saves interactions for each cell.

**Comment by phisn** [comment]
For future readers. I decided to use [bevy_xpbd](https://github.com/Jondolf/bevy_xpbd) where I am able to define a [custom broad phase](https://github.com/Jondolf/bevy_xpbd/blob/main/crates/bevy_xpbd_3d/examples/custom_broad_phase.rs). My idea is to now ignore all collisions between entities with Particle components. Additionally I don't have to deal with having two rapier contexts (this is needed since I can not put my particles in the existing physics simulation since I need determinism).
