### ISSUE TITLE
2D Rigidbody type changing from Kinematic->Dynamic at runtime doesn't work

### ISSUE THREAD

**Issue by miwarnec** [dimforge/rapier#616]
I create a 2D **KinematicPosition** Rigidbody.
Change it to **Dynamic** 3 seconds later.
Apply a velocity in every update afterwards.

The Rigidbody never moves again after it was kinematic once.

---

Same happens if I create a **Dynamic** Rigidbody.
Change to **Kinematic**.
Change back to **Dynamic** 3 seconds later.
Applying velocity never movies it again.

**Comment by MaxCWhitehead** [comment]
This may have been fixed in #599

**Comment by Vrixyz** [comment]
I confirm I couldn't reproduce (tested in cfcbe58920d7fa2177e9a188)
