### ISSUE TITLE
parry2d v0.15.0 yanked

### ISSUE THREAD

**Issue by lylythechosenone** [dimforge/rapier#631]
`rapier2d`'s dependency should be updated to v0.15.1.

**Comment by sebcrozet** [comment]
Updating the dependency explicitly shouldn’t be needed as cargo will automatically find `0.15.1` due to semver versioning. I’m guessing you need to run a `cargo update`?

**Comment by lylythechosenone** [comment]
You are correct, it is automatic, but it would be good to explicitly update it here anyway. It's not something that needs an immediate new release, but should be fixed for the next one.

**Comment by Vrixyz** [comment]
I guess we can wait for next version, but another inconveniance is that documentaion links are currently a bit broken: following `SharedShape` from [`Collider`](https://docs.rs/bevy_rapier2d/latest/bevy_rapier2d/geometry/struct.Collider.html) links to the yanked version https://docs.rs/parry2d/0.15.0/parry2d/shape/struct.SharedShape.html

**Comment by lylythechosenone** [comment]
Yes, that's exactly how I noticed it.

**Comment by waywardmonkeys** [comment]
This is fixed in rapier 0.21 which updated to parry 0.16 in 3004a7d38da447e307e11d86528047bdb724c318
