### ISSUE TITLE
Rapier's "parallel" feature doesn't enable Parry's "parallel" feature

### ISSUE THREAD

**Issue by waywardmonkeys** [dimforge/rapier#687]
Should the "parallel" feature in Rapier enable the "parallel" feature in Parry?

**Comment by Vrixyz** [comment]
parallel feature from parry exists "only" to add more functions to the Qbvh ( see https://github.com/Vrixyz/parry/blob/5b17c9830d65453e3a9b3c8a0efa719b303130c7/src/partitioning/qbvh/traversal.rs#L504 ) ; and they's not used so we don't want to enable that feature.

It might be to reconsider if/when we need those functions.
