### ISSUE TITLE
2D Trimesh seems broken

### ISSUE THREAD

**Issue by msvbg** [dimforge/rapier#7]
Here's a quick and dirty reproduction repo for the bug I described yesterday on Discord: https://github.com/msvbg/rapier-trimesh-problem-reproduction. `cargo run` is enough to run it. The little cube is controlled with WASD, and if you try to hit the static piece of geometry, which is defined by a Rapier trimesh, the collision response is a little bit weird. Turning on `simd-stable` causes a panic.

Apologies for the messy code, but even getting it down to this state was a fair bit of work...

**Comment by sebcrozet** [comment]
Thank for the code for reproducing the bug. Triangle meshes have not been tested in 2D yet so more work will be needed to make them behave correctly in 2D.

**Comment by robert-hrusecky** [comment]
After downloading your reproduction repo and updating it to the latest version, it appears that the collision response issues have been fixed. Also, I am no longer able to trigger the panic with `simd-stable`.

**Comment by robert-hrusecky** [comment]
After some digging, it seems like some of the issues are coming from `cuboid_triangle_contact_generator.rs`:
 - The function call `sat::triangle_cuboid_find_local_separating_normal_oneway` in 2D tries to get a surface normal by taking a cross product.
 - `triangle::support_face` appears to be `unimplemented!()`.

@sebcrozet, was there a specific reason this function was left unimplemented? I just want to double check what your thoughts are before going ahead and trying to implement it.
