### ISSUE TITLE
Headless Testbed with Metrics?

### ISSUE THREAD

**Issue by JulianKnodt** [dimforge/rapier#702]
Hey, I'm using Rapier to evaluate the performance of collider meshes, and have been using the testbed app. I was wondering if there's an easy way to run the testbed app without graphics and to get the FPS at each frame programmatically? I checked the docs and didn't look like there was an easy way, but wanted to ask before reimplementing part of it.

Thanks!

**Comment by Vrixyz** [comment]
There is a benchmark mode for the testbed, which you can enable by passing `--bench`, like `cargo run --bin all_benchmarks3 -- --bench --example boxes` ; which will output a csv of frame durations in milliseconds

**Comment by JulianKnodt** [comment]
Neato, this does what I hope for, but it also is hardcoded to 1000 frames ([here](https://github.com/dimforge/rapier/blob/b7347860f71179a4675ec785644abe1bb09e415a/src_testbed/testbed.rs#L287)). It also seems the help message doesn't actually show that `--bench` is an option. Is that something that would be amenable to be changed in a PR?

**Comment by Vrixyz** [comment]
Indeed, the arguments handling is not great 🫂

Pull requests for improving the help message and/or the hardcoded `args` handling are welcome!
