### ISSUE TITLE
Why does FixedJoint allow some rotation?

### ISSUE THREAD

**Issue by HoutarouOreki** [dimforge/rapier#709]
I have a car body, to which an axle is connected (big box) through a RevoluteJoint (Y), and to the axle I've connected an arm through a FixedJoint, and to the arm a wheel is connected through a RevoluteJoint (X).

[body] --1-- [axle] --2-- [arm] --3-- [wheel]

1 = RevoluteJoint Y
2 = FixedJoint
3 = RevoluteJoint X

I need to have completely no rotation between the axle and the arm, and I thought FixedJoint would do that. But it allows a bit of rotation for some reason? Did I miss anything in the docs?

https://github.com/user-attachments/assets/5108ddc9-b121-4579-82ac-28d687f5f738

https://github.com/user-attachments/assets/a5c164ed-283d-44d0-a0f4-1f8e66e8dc46

```rs
    let camber_arm_joint = FixedJointBuilder::new()
        .local_anchor1(camber_arm_offset)
        .local_anchor2(Vec3::ZERO)
        .build();

    commands
        .entity(camber_arm)
        .insert(ImpulseJoint::new(axle, camber_arm_joint))
```

**Comment by one-for-all** [comment]
Have you tried using MultibodyJoint instead?

**Comment by HoutarouOreki** [comment]
No, gave up on trying to use them, can't find information on what they're supposed to be. The only thing they seem to do for me is exploding everything.

The impulse joints work fine with more simulation steps and bodies' mass adjustments.
