### ISSUE TITLE
cargo test fails in build/rapier2d & build/rapier3d

### ISSUE THREAD

**Issue by rezural** [dimforge/rapier#84]
cargo test fails if run from within the build/rapier{2d,3d} directories.

running cargo test --workspace however doesnt.

I'm not sure if this is a real issue, or not, but I'm putting it up here just in case.

**Comment by rezural** [comment]
cargo test --features=serde-serialize works, so this may be a non issue. A bit surprising though.

**Comment by sebcrozet** [comment]
Closing. This is no longer an issue.
