### ISSUE TITLE
bevy_rapier documentation incorrect

### ISSUE THREAD

**Issue by faassen** [dimforge/rapier#85]
When I use the `main.rs` copied  from the documentation it doesn't compile.

This is because I had to replace `mut commands: Commands` with `commands: &mut Commands) as the former isn't compatible with the latest bevy.

After that it compiles, but when I run this I get the following crash:

```
thread 'TaskPool (22)' panicked at 'Resource does not exist bevy_core::time::time::Time.',

I can trigger the same error if I reference `time: Res<Time>` myself, so it appears that's the underlying cause; the physics plugin assumes a resource is there that isn't there. This clued me in that it depends on the existence of the bevy default plugins.

So the documentation should also be updated to include:

```
 .add_plugins(DefaultPlugins)
```

After that it compiles and runs.

**Comment by sebcrozet** [comment]
The doc has been updated.
