### ISSUE TITLE
Clean up warnings

### ISSUE THREAD

**Issue by emilk** [dimforge/rapier#92]
There are half a dozen or so warnings generated when building `rapier3d` (unused imports and unused functions). Ignoring these warnings when compiling may lead to us ignoring more serious warnings.

It would be good to forbid warnings in CI and/or by adding this to `lib.rs`:

``` rust
#![cfg_attr(not(debug_assertions), deny(warnings))] // Forbid warnings in release builds
```

**Comment by sebcrozet** [comment]
Using `deny(warnings)` is [considered a bad practice](https://github.com/rust-unofficial/patterns/blob/master/anti_patterns/deny-warnings.md) so disabling warnings on the CI sounds like the right option. This will be part of #79: it's a large refactoring so I might as well fix all the warnings there and add the CI check.

**Comment by sebcrozet** [comment]
Sorry, I closed this by mistake, reopening.
